#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".py\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nLinting Python:\n"

# Check for eslint
which flake8 &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install flake8\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  flake8 "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mflake8 Passed: $FILE\033[0m"
  else
    echo "\t\033[41mflake8 Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nPython linting completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass flake8 but do not. Please fix the flake8 errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
