fail_fast: false
default_language_version:
    python: python3.10
repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3.10
      files: (notes|users)

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
    - id: reorder-python-imports
      files: (mantik|tests)

