"""initialise db schema

Revision ID: 8edcd87472f6
Revises:
Create Date: 2025-05-10 22:52:25.054518

"""

from alembic import op
import sqlalchemy as sa
from repository.adapter.tables.fields.passwordField import Password

# revision identifiers, used by Alembic.
revision = '8edcd87472f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'movie_info',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('date_created', sa.BigInteger(), nullable=True),
		sa.Column('date_updated', sa.BigInteger(), nullable=True),
		sa.Column('title', sa.String(), nullable=False),
		sa.Column('description', sa.String(), nullable=True),
		sa.Column('release_year', sa.BigInteger(), nullable=True),
		sa.Column('active', sa.Boolean(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_table(
		'user_info',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('date_created', sa.BigInteger(), nullable=True),
		sa.Column('date_updated', sa.BigInteger(), nullable=True),
		sa.Column('name', sa.String(), nullable=False),
		sa.Column('activation_code', sa.String(), nullable=True),
		sa.Column('activation_expiry_date', sa.BigInteger(), nullable=True),
		sa.Column('password', Password(), nullable=False),
		sa.Column('active', sa.Boolean(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('name'),
	)
	op.create_table(
		'rating_info',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('date_created', sa.BigInteger(), nullable=True),
		sa.Column('date_updated', sa.BigInteger(), nullable=True),
		sa.Column('movie_info_id', sa.Integer(), nullable=False),
		sa.Column('user_info_id', sa.Integer(), nullable=False),
		sa.Column('review', sa.String(), nullable=True),
		sa.Column('rating', sa.Integer(), nullable=True),
		sa.Column('active', sa.Boolean(), nullable=False),
		sa.ForeignKeyConstraint(['movie_info_id'], ['movie_info.id'], ondelete='CASCADE'),
		sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ondelete='CASCADE'),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_table(
		'rating_report',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('date_created', sa.BigInteger(), nullable=True),
		sa.Column('date_updated', sa.BigInteger(), nullable=True),
		sa.Column('movie_info_id', sa.Integer(), nullable=False),
		sa.Column('accumulated_rating', sa.Numeric(precision=10, scale=2), nullable=True),
		sa.ForeignKeyConstraint(['movie_info_id'], ['movie_info.id'], ondelete='CASCADE'),
		sa.PrimaryKeyConstraint('id'),
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('rating_report')
	op.drop_table('rating_info')
	op.drop_table('user_info')
	op.drop_table('movie_info')
	# ### end Alembic commands ###
