# Generated by Django 4.1.2 on 2022-10-10 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "modified_date",
                    models.DateField(auto_now_add=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "modified_date",
                    models.DateField(auto_now_add=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="notes.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
                "abstract": False,
            },
        ),
    ]
