"""empty message

Revision ID: 853b4a96f217
Revises: 818ef83523ce
Create Date: 2024-03-19 22:10:52.901810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853b4a96f217'
down_revision = '818ef83523ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_vote_average', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_vote_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('tmdb_vote_count')
        batch_op.drop_column('tmdb_vote_average')

    # ### end Alembic commands ###
