from pydantic import BaseModel, Field


class CreateUserAPIRequest(BaseModel):
    name: str = Field(
        ..., description='User name, could be also the email address', min_length=4, max_length=16
    )
    password: str = Field(..., min_length=4, max_length=16)

    class Config:
        json_schema_extra = {
            'example': {
                'name': 'Dark night',
                'password': '***',
            }
        }


class ChangePasswordAPIRequest(BaseModel):
    name: str = Field(
        ..., description='User name, could be also the email address', min_length=4, max_length=16
    )
    activation_code: str = Field(
        ...,
        description='The activation ocde which generated by the system to verify the password change',
        min_length=4,
        max_length=16,
    )
    password: str = Field(..., description='new password', min_length=4, max_length=16)

    class Config:
        json_schema_extra = {
            'example': {'name': 'Dark night', 'password': '***', 'activation_code': '***'}
        }


class ForgotPasswordAPIRequest(BaseModel):
    name: str = Field(
        ..., description='User name, could be also the email address', min_length=4, max_length=16
    )

    class Config:
        json_schema_extra = {
            'example': {
                'name': 'Dark night',
            }
        }


class ActivationRequest(BaseModel):
    name: str = Field(
        ..., description='User name, could be also the email address.', min_length=4, max_length=16
    )
    token: str = Field(
        ..., description='Activation token generated by the system', min_length=4, max_length=32
    )

    class Config:
        json_schema_extra = {'example': {'name': 'Dark night', 'token': 'activation token'}}
