name: Movie Rating System 🍿

on:
  pull_request:
    branches:
      - main

jobs:
  cancel-previous:
    name: Cancel Previous
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint 🎞️
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
